### ISSUE TITLE
Rolling Upgrades

### ISSUE THREAD

**Issue by Supernomad** [Supernomad/quantum#59]
`quantum` theoretically has the ability to preform a seamless rolling restart, given that the file descriptors can be passed during a fork-exec operation. According to the go documentation this is possible, so the idea would be to start a new quantum instance but pass in the file descriptors of the TUN and Sockets. 

This would effectively allow for the current `quantum` instance to gracefully terminate, without losing packets.

**Comment by tlloydaubry** [comment]
Cooool
